# Classes

In [ ]:
class MyClass:
    variable = 'Hello' # only defined inside the class; local varaible

    def my_function(self): # join all the function and class to each other?
        print("This is a message inside the class")

my_object = MyClass()

print(my_object.variable) # . refers to something inside the class

print(MyClass().variable)

my_object.my_function() # runs the function inside the class

Hello
Hello
This is a message inside the class


In [ ]:
my_object1 = MyClass()
my_object2 = MyClass()

In [ ]:
class Person:
    name = "Ben"
    age = 35

    def ethnicity(self, e):
        print(name) # notice how there's a squiggly. variable name is not global
        

In [10]:
class Person:
    def __init__(self, name = None, age = None): # need init for variables to be global
        self.name = name # self allows name to be global
        self.age = age
        self.school = "CSULB" # fixed variable

    def ethnicity(self, e):
        print(self.name) # name is now access by other functions through "self."
        self.e = e
        if self.name is None:
            self.name = input("Please enter a name for the person: ")
        elif self.age is None:
            self.age = input("Please entere an age for the person: ")

        print("My name is ", self.name, ". My age is ", self.age, ". My ethnicity is ", self.e)


p1 = Person(age = 36)
p2 = Person("Jack", 54)
p3 = Person()

p1.ethnicity("White")
p2.ethnicity("Black")


None
My name is  John . My age is  36 . My ethnicity is  White
Jack
My name is  Jack . My age is  54 . My ethnicity is  Black


In [13]:
class Bag:
    def __init__(self):
        self.data = []
    
    def add(self, x):
        self.data.append(x)

    def addtwice(self, x):
        self.add(x)
        self.add(x)

    def add_n_times(self, x, n):
        for i in range(n):
            self.add(x)

My_Bag = Bag()
My_Bag.add(1)
My_Bag.add_n_times(2, n=3)
My_Bag.add([4,5])
print(My_Bag.data)


[1, 2, 2, 2, [4, 5]]


In [ ]:
class my_sum:
    def add_f(self, a, b):
        return a + b

class math_op:
    def sum_three_in(self, a, b, c):
        x = my_sum().add_f(a,b)
        y = my_sum().add_f(x,c)
        return y
    
print(math_op().sum_three_in(1,2,3))
    



6


# Numpy

In [21]:
import numpy as np # powerful for math op

a = np.array([1,2,3]) # dont know if column or row vector. make sure to reshape

print('initial a:' , a)

a = a.reshape((3,1)) # column vector

print('initial column a:' , a)

a = a.reshape((1,3)) # row vector

print('initial row a:' , a)



initial a: [1 2 3]
initial column a: [[1]
 [2]
 [3]]
initial row a: [[1 2 3]]


In [23]:
a = np.array([[1,2], [3,4]])
a.shape

(2, 2)

In [27]:
a = np.array([1,2,3,4,5,6])
b = np.array([1,2,3,4,5,6], ndmin = 2) #ndmin = number of dimensions
c = np.array([1,2,3,4,5,6], ndmin = 1)
d = np.array([1,2,3,4,5,6], ndmin = 3)

# reshape or define dimension to turn it into a row dimension
print(a)
print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)





[1 2 3 4 5 6]
(6,)
(1, 6)
(6,)
(1, 1, 6)


In [28]:
a = np.array([1,2,3,4,5,6], dtype = float)

print(a)

[1. 2. 3. 4. 5. 6.]


In [30]:
x = np.empty([3,2], ndmin = 2)
x 

TypeError: empty() got an unexpected keyword argument 'ndmin'

In [ ]:
print(a)
print(b)

In [ ]:
c = b * -1

In [ ]:
c = np.concatenate((a,b), axis = 0) # 0 means column
c

In [33]:
a = [[1,2], [3,4]] # the sizes in the list must be the same
# a = [[1,2], [3,4,5]] # error!
print(type(a))

a = np.asarray(a)
print(type(a))
print(a)


<class 'list'>
<class 'numpy.ndarray'>
[[1 2]
 [3 4]]


In [ ]:
a = np.array([1,2,3,4,5,6], dtype = float)
b = np.array([11,22,33,44,55,66], dtype = float)

print(a*b) # element-wise multiplication
print(a+b)
print(a**b)


[ 11.  44.  99. 176. 275. 396.]
[12. 24. 36. 48. 60. 72.]
[1.00000000e+00 4.19430400e+06 5.55906057e+15 3.09485010e+26
 2.77555756e+38 2.28025032e+51]
1001.0


In [41]:
a = [[1,2], [3,4]] 
b = [[10,20], [30,40]] 

print(a)
print(b)

c = np.dot(a,b)

print(c)


[[1, 2], [3, 4]]
[[10, 20], [30, 40]]
[[ 70 100]
 [150 220]]


In [ ]:
# space = ( floor(stop - start / N) + 1)
# what is N?
# ((20 - 10) / .5 ) + 1 ==> 

x = np.linspace(10,20, 23)
x

array([10.        , 10.45454545, 10.90909091, 11.36363636, 11.81818182,
       12.27272727, 12.72727273, 13.18181818, 13.63636364, 14.09090909,
       14.54545455, 15.        , 15.45454545, 15.90909091, 16.36363636,
       16.81818182, 17.27272727, 17.72727273, 18.18181818, 18.63636364,
       19.09090909, 19.54545455, 20.        ])